### ISSUE TITLE
'class LinkItWifi' has no member named 'html_title'

### ISSUE THREAD

**Issue by dhananjai-bajpai** [swampyness/wrappers_linkit#1]
'class LinkItWifi' has no member named 'html_title', in the linkit_dashboard.ino code which uses wrapper_linkit_cam.cpp file. Can you guide me how can I compile this code without errors.

Similarly wifi.span does not exist in the wrapper_linkit_cam.cpp file, do I need to write these functions into this file, because they are called in the main code, but they do not exist in the wrapper_linkit_cam.cpp file.

**Comment by matchygames** [comment]
I've updated wrapper_linkit_wifi.cpp with the inclusion of wifi.span now.

html_title is declared in where the file is stored like this:
Documents\Arduino\libraries\wrapper_linkit_wifi\wrapper_linkit_wifi.h

**Comment by swampyness** [comment]
I've updated wrapper_linkit_wifi.cpp with the inclusion of wifi.span now.

html_title is declared in where the file is stored like this:
Documents\Arduino\libraries\wrapper_linkit_wifi\wrapper_linkit_wifi.h

**Comment by dhananjai-bajpai** [comment]
Can I get the updated version of this library, which has updated member as 'html_title' and 'wifi.span'?

Should I download the wrappers_linkit libraries again?

**Comment by dhananjai-bajpai** [comment]
Can I get the updated version of this library, which has updated member 
as 'html_title' and 'wifi.span'?

Should I download the wrappers_linkit libraries again?

**Comment by swampyness** [comment]
You haven't noticed I updated it yesterday so, yeah, just download it again!

**Comment by dhananjai-bajpai** [comment]
Thanx, I got the updated part of the code

**Comment by dhananjai-bajpai** [comment]
Thanx for the help, It uploads without any error now. But there is a new 
problem, here it:-

After successfully compiling and uploading the "linkit_dashboard" code, 
when serial terminal is opened with "Debug Port" to get the targeted IP 
address, only "Re-connecting to AP" message is printed.

Just like in UDP code (example of LinkIt-wifi) do I need to update SSID, 
Password, Local Port numbers in the "linkit_dashboard" or in 
"wrapper_linkit_wifi.cpp" file somewhere, so that I can get the IP 
address and upload my pics via serial camera.

**Comment by swampyness** [comment]
Edit the wrapper_linkit_wifi.h file to change:

```
    #define WIFI_AP         "your_wifi_name"
    #define WIFI_PASSWORD   "your_wifi_password"
```

The port is default 80. Edit wrapper_linkit_wifi.cpp to change:

```
             LWiFiServer server(80);
```

**Comment by dhananjai-bajpai** [comment]
Thank you again, I fixed all three parameters and I am able to get many 
IP addresses in the serial terminal

After feeding one on the address bar, It says "Web page can't be 
Reached", I have attached an Image to my current problem

Please check the attachment in this email.

**Comment by dhananjai-bajpai** [comment]
![web_page unavailable](https://cloud.githubusercontent.com/assets/18440699/14520026/dd8b2890-023f-11e6-9ad3-ce0bc8566868.PNG)

Please check this image, for the overview of my problem

**Comment by matchygames** [comment]
Try http:// instead of https://

**Comment by dhananjai-bajpai** [comment]
I have tried both http and https
Should i pick up any specific IP address from the list of addresses that 
I am getting? I have tried atleast 10 of them, but the web page can not 
be reached. Am I missing any setting somewhere?

**Comment by dhananjai-bajpai** [comment]
One more thing to notice is that Terminal shows 10.21.29 on feeding this 
in browser's address bar it automatically becomes https://10.21.0.29/
0 is stuffed in automatically between 10.21..29

Is there any correction that are required to be done in getting the IP 
address from the LinkIt module?

**Comment by matchygames** [comment]
The screenshot above is displaying the GPS time each second, not the IP address. Comment it out in linkit_dashboard.ino

//              Serial.println(globe.view[S_TIME]);

**Comment by dhananjai-bajpai** [comment]
After commenting out Serial.println(globe.view[S_TIME]);
Nothing comes on the terminal, I think I am missing something, how can I 
get the targeted IP address, what should be changed to print the IP 
address.

**Comment by dhananjai-bajpai** [comment]
In the void LinkItWifi::web() function present in the 
wrapper_linkit_wifi.cpp, nothing gets printed on the terminal, may be 
because I am missing some settings?
Can you guide me in pulling out the targeted IP address from your code?

**Comment by dhananjai-bajpai** [comment]
I can see that in the linkit_dashboard code uploaded on git hub, is not 
calling "get_ip()" in the main code?

Are you calling it internally somewhere because in the main code it is 
not called, may be that is why i am not getting an IP address?

**Comment by dhananjai-bajpai** [comment]
In the "wrapper_linkit_wifi.cpp" one issue is that nothing gets executed 
after client = server.available();

Thus statements inside "if (client)" in same, are never executed, is 
their a problem in my wi-fi settings? Am I missing some wi-fi 
configuration setting?

**Comment by dhananjai-bajpai** [comment]
Thanks for you support, ultimately I was able to replicate your stuff 
and solve my problem.

There were few changes the I had to do on the hardware side, once they 
were done your code had NO errors.

It works with 100% accuracy, thanxx again!! excellent work!!

**Comment by dhananjai-bajpai** [comment]
![dashboard_webpage](https://cloud.githubusercontent.com/assets/18440699/14527702/4f43ad3a-0269-11e6-9673-4466b8544e2b.PNG)
![capture](https://cloud.githubusercontent.com/assets/18440699/14527712/5d4948b8-0269-11e6-8316-46ddbcb97c40.PNG)
