### ISSUE TITLE
Post image in other Webpage instead of hosting one over LinkIt one module

### ISSUE THREAD

**Issue by dhananjai-bajpai** [swampyness/wrappers_linkit#2]
After successfully executing dashboard code and snapping images over serial camera to webpage. I want to post this image to a particular webpage. Can you suggest how can I send my image to other webpage, instead of hosting a server on linkit one module.

Do I need to edit LWiFi.cpp library for sending image to other webpage?

**Comment by swampyness** [comment]
The dashboard was really designed just for minor system tests. This serial camera code pushes the JPG data stream in low frame rate to directly to port 80. Sending the image to another server still requires a LinkIt server of some  sort. Anyhow, in a real world project, I would be using the Raspberry Pi 3 to display stable webpage.

**Comment by dhananjai-bajpai** [comment]
I am already having my web server hosted on Raspberry Pi3 with default 
port 8090, I want transfer this data to my webpage, instead of hosting a 
server, I want to route it to my server, so that it can be remotely 
accessed.

Is there any way that can be used in transferring data from linkit one 
wifi module to a particular server?

Can you tell me where does these LinKIt libraries like LWiFi.h, LGPS.h 
are stored in arduino? I want to see these libraries and modify them, 
but I can not locate them on my system, although arduino includes them, 
but from where does it picks up these libraries?

**Comment by swampyness** [comment]
The libraries are stored here:
C:\Program Files (x86)\Arduino\hardware\arduino\mtk\libraries

**Comment by dhananjai-bajpai** [comment]
Yes, can you suggest me a way to send the snapshot to my web server, so 
that it can be accessed from any one at anytime.

**Comment by dhananjai-bajpai** [comment]
Is there any example code, that can take a snapshot and send it to a 
particular server, or may be a simple example of sending a string to a 
server?

**Comment by swampyness** [comment]
Would you like me to make you something?

**Comment by dhananjai-bajpai** [comment]
I am not in a position to take a call on that

**Comment by swampyness** [comment]
Have a good day.
